### ISSUE TITLE
Postback aborted because validation failed - dialog

### ISSUE THREAD

**Issue by PavelBansky** [riganti/dotvvm-samples-academy#10]
I'm getting this "Postback aborted because validation failed." dialog in the top right corner, when validation fails.
I'm I doing something wrong or is it a intent?

**Comment by exyi** [comment]
This message is displayed by dotvvm only if `DotvvmConfiguration.Debug == true`, and it is intended behavior. You are not doing anything wrong, we should just probably deploy dotvvm academy on Prodution environment.

**Comment by tomasherceg** [comment]
In which situation you get this error? 
I have been clicking in the app for a while and haven't seen the dialog. 

Or do you run it locally? In that case, it is normal - it show this popup in the debug mode because if you didn't have validators in the page, you would not know why the postback is not being invoked.

**Comment by PavelBansky** [comment]
Yes, I'm running locally with `DotvvmConfiguration.Debug == true` .
When build as Release and deployed, the dialog is not present :)
